---

# - name: Create influxdb group
#   group:
#     name: "{{influxdb_group}}"
#     state: present
#   tags:
#     - influxdb
#
# - name: Create influxdb user
#   user:
#     name: "{{influxdb_user}}"
#     group: "{{influxdb_group}}"
#     state: present
#   tags:
#     - influxdb

- name: Download version
  get_url:
    url: "{{influxdb_dl_url}}"
    dest: "{{influxdb_pkg}}"
  tags:
    - influxdb

- name: Install package
  command: "dpkg --skip-same-version -i /usr/local/src/influxdb_{{ influxdb_ver }}_{{ influxdb_arch }}.deb"
  register: dpkg_result
  changed_when: "dpkg_result.stdout.startswith('Selecting')"
  when: ansible_distribution in ['Ubuntu', 'Debian']
  tags:
    - influxdb

- name: Create data dir
  file:
    path: "{{influxdb_data_dir}}"
    state: directory
    group: "{{influxdb_group}}"
    owner: "{{influxdb_user}}"
  tags:
    - influxdb

- name: Create meta dir
  file:
    path: "{{influxdb_meta_dir}}"
    state: directory
    group: "{{influxdb_group}}"
    owner: "{{influxdb_user}}"
  tags:
    - influxdb

- name: Create hh dir
  file:
    path: "{{influxdb_hh_dir}}"
    state: directory
    group: "{{influxdb_group}}"
    owner: "{{influxdb_user}}"
  tags:
    - influxdb

- name: Create wal dir
  file:
    path: "{{influxdb_wal_dir}}"
    state: directory
    group: "{{influxdb_group}}"
    owner: "{{influxdb_user}}"
  tags:
    - influxdb

- name: Create config directory
  file:
    path: "{{influxdb_config_dir}}"
    state: directory
    group: "{{influxdb_group}}"
    owner: "{{influxdb_user}}"
  tags:
    - influxdb

- name: Write config
  template:
    src: "conf{{influxdb_conf_ver}}.j2"
    dest: "{{influxdb_config_file}}"
    group: "{{influxdb_group}}"
    owner: "{{influxdb_user}}"
  notify:
    - restart influxdb
  tags:
    - influxdb

- name: Ensure directories have correct permissions
  command: "sudo chown -c -R {{influxdb_group}}:{{influxdb_user}} {{item}}"
  with_items:
    - "{{influxdb_meta_dir}}"
    - "{{influxdb_data_dir}}"
    - "{{influxdb_hh_dir}}"
    - "{{influxdb_wal_dir}}"
  register: result
  changed_when: result.stdout != ""
  tags:
    - influxdb

- name: Start influxdb service
  service:
    name: influxdb
    state: started
  tags:
    - influxdb
